import { WeaponDef, FoodItem, Quest, PlayerSimsProfile } from './types.ts';

export const WEAPONS: Record<string, WeaponDef> = {
  ar: {
    id: 'ar',
    name: 'Lekki Sweeper AK-47',
    category: 'AR',
    damage: 34,
    fireRate: 9, // rounds per sec
    magSize: 30,
    maxReserve: 150,
    reloadTime: 2.0,
    range: 75,
    accuracy: 0.88,
    recoil: 0.12,
    costNaira: 45000,
    description: 'High caliber street workhorse. Heavy stopping power with distinctive wooden stock and gold engravings.',
  },
  smg: {
    id: 'smg',
    name: 'Oshodi Rapid SMG',
    category: 'SMG',
    damage: 22,
    fireRate: 14,
    magSize: 40,
    maxReserve: 200,
    reloadTime: 1.6,
    range: 45,
    accuracy: 0.82,
    recoil: 0.08,
    costNaira: 32000,
    description: 'Ultra fast run-and-gun submachine gun. Shreds enemies in close-quarters market alleyways.',
  },
  sniper: {
    id: 'sniper',
    name: 'Zaria Longshot',
    category: 'SNIPER',
    damage: 110,
    fireRate: 1.2,
    magSize: 5,
    maxReserve: 30,
    reloadTime: 3.2,
    range: 150,
    accuracy: 0.98,
    recoil: 0.35,
    costNaira: 65000,
    description: 'High-precision marksman rifle. One shot to upper chest or head neutralizes targets instantly.',
  },
  melee: {
    id: 'melee',
    name: 'Bar Beach Cutlass',
    category: 'MELEE',
    damage: 75,
    fireRate: 2.2,
    magSize: 1,
    maxReserve: 1,
    reloadTime: 0.1,
    range: 3.5,
    accuracy: 1.0,
    recoil: 0,
    costNaira: 10000,
    description: 'Polished street blade. Silent and lethal in tight compound skirmishes.',
  },
  tactical: {
    id: 'tactical',
    name: 'Suya Pepper Bomb',
    category: 'TACTICAL',
    damage: 40,
    fireRate: 0.8,
    magSize: 2,
    maxReserve: 4,
    reloadTime: 1.0,
    range: 30,
    accuracy: 0.9,
    recoil: 0,
    costNaira: 8000,
    description: 'Concentrated spicy habanero pepper smoke canister that blinds and disorients hostile squads.',
  },
};

export const FOOD_MENU: FoodItem[] = [
  {
    id: 'jollof',
    name: 'Smokey Party Jollof',
    costNaira: 1500,
    energyBonus: 40,
    healthBonus: 30,
    vibeBonus: 20,
    description: 'Authentic firewood-cooked Lagos party jollof with fried plantain and pepper sauce.',
    tagline: 'Gives +40 Energy and restores 30 HP!',
  },
  {
    id: 'suya',
    name: 'Aboki Spicy Beef Suya',
    costNaira: 2500,
    energyBonus: 60,
    healthBonus: 40,
    vibeBonus: 40,
    description: 'Thinly sliced seasoned beef smoked over glowing embers with extra Yaji pepper and red onions.',
    tagline: 'Max vibes! Activates +20% sprint speed boost for 45s.',
  },
  {
    id: 'puffpuff',
    name: 'Golden Puff-Puff Trio',
    costNaira: 600,
    energyBonus: 20,
    healthBonus: 10,
    vibeBonus: 15,
    description: 'Sweet, chewy fried dough balls hot from the pan.',
    tagline: 'Quick energy snack on the go.',
  },
  {
    id: 'malt',
    name: 'Chilled Super Malt & Milk',
    costNaira: 1200,
    energyBonus: 50,
    healthBonus: 25,
    vibeBonus: 25,
    description: 'Ice-cold nourishing malt drink mixed with condensed milk. Instant revitalizer.',
    tagline: 'Restores stamina and clears weapon recoil fatigue.',
  },
];

export const INITIAL_PROFILE: PlayerSimsProfile = {
  name: 'Tunde Odogwu',
  alias: 'GHOST-01 LAGOS',
  title: 'Street Tactical Specialist',
  naira: 28500,
  streetCred: 240,
  jollofEnergy: 85,
  vibes: 90,
  outfit: {
    head: 'Afro Bucket Hat',
    vest: 'Ankara Tactical Kevlar',
    pants: 'Combat Cargo Denim',
    accessory: 'Gold Chain & Dogtags',
  },
  unlockedOutfits: [
    'Afro Bucket Hat',
    'VR Cyber Visor',
    'Commander Beret',
    'Ankara Tactical Kevlar',
    'Lagos Street Hoodie',
    'Combat Cargo Denim',
    'Gold Chain & Dogtags',
  ],
  upgrades: {
    extendedMag: true,
    redDotSight: false,
    suyaAdrenaline: false,
    bulletproofAnkara: false,
  },
};

export const INITIAL_QUESTS: Quest[] = [
  {
    id: 'q1',
    title: 'Clean Up Balogun Crossing',
    targetCount: 5,
    currentCount: 0,
    rewardNaira: 15000,
    rewardCred: 120,
    description: 'Neutralize 5 hostile Agbero Syndicate bots in the Balogun street market zone.',
    completed: false,
  },
  {
    id: 'q2',
    title: 'Mama Put Sustenance',
    targetCount: 2,
    currentCount: 0,
    rewardNaira: 6000,
    rewardCred: 60,
    description: 'Fuel up with 2 hearty meals from Mama Put’s tactical kitchen to stay alert.',
    completed: false,
  },
  {
    id: 'q3',
    title: 'Odogwu Headshot Mastery',
    targetCount: 3,
    currentCount: 0,
    rewardNaira: 25000,
    rewardCred: 180,
    description: 'Execute 3 clean headshots during skirmish combat.',
    completed: false,
  },
  {
    id: 'q4',
    title: 'Danfo Convoy Guardian',
    targetCount: 1,
    currentCount: 0,
    rewardNaira: 35000,
    rewardCred: 250,
    description: 'Successfully escort the yellow Danfo bus to the safe-zone checkpoint.',
    completed: false,
  },
];

export const PIDGIN_CALLOUTS = [
  'Headshot o! Oya clear road!',
  'E choke! Odogwu move!',
  'Wetin dey happen! Cover me!',
  'No shaking! Reloading now!',
  'Enemy down! One for the road!',
  'Area boy neutralized!',
  'Danfo strike incoming!',
  'Jollof power fully charged!',
  'Odogwu double kill confirmed!',
];

export const LAGOS_DISTRICTS = [
  {
    id: 'LEKKI',
    name: 'Lekki Phase 1 & Marina',
    subtitle: 'Skyscrapers & Coastal Link Bridge',
    center: { x: 60, z: -60 },
    color: '#38bdf8',
    description: 'Modern glass towers, luxury penthouses, palm boulevards, and the iconic Lekki-Ikoyi suspension bridge on the lagoon horizon.',
  },
  {
    id: 'BALOGUN',
    name: 'Balogun Island Market',
    subtitle: 'Dense Labyrinth Market & Alleys',
    center: { x: -60, z: -60 },
    color: '#f59e0b',
    description: 'Vibrant multi-story trading houses, colorful umbrella stalls, textile bales, and tight alleys for stealth skirmishes.',
  },
  {
    id: 'OSHODI',
    name: 'Oshodi Transport Interchange',
    subtitle: 'Danfo Bus Terminal & Flyover Hub',
    center: { x: -60, z: 60 },
    color: '#ffd000',
    description: 'The heartbeat of Lagos transit. Yellow Danfo bus parks, ticket shacks, overhead pedestrian bridges, and busy traffic roundabouts.',
  },
  {
    id: 'COMPUTER_VILLAGE',
    name: 'Computer Village Ikeja',
    subtitle: 'Tech Bazaars & Generator Alley',
    center: { x: 60, z: 60 },
    color: '#10b981',
    description: 'West Africa’s tech capital. Giant electronics billboards, humming generator banks, cyber cafes, and gadget technician compounds.',
  },
  {
    id: 'CENTRAL_ROUNDABOUT',
    name: 'Tinubu Heritage Roundabout',
    subtitle: 'Central Monument & City Junction',
    center: { x: 0, z: 0 },
    color: '#ec4899',
    description: 'The beating center of the metropolis connecting all 4 main boulevards with a landmark statue plaza.',
  },
];

